name: LotteriaBox
version: 1.1
main: com.playernguyen.lotteriabox.LotteriaBox
depend:
  - Weaponist
commands:
  lotteriabox:
    description: The LotteriaBox command plugin
    usage: /lotteriabox ...
    aliases: [lbox, lb]